### ISSUE TITLE
python 3.10 venv內底，`pip install`錯誤

### ISSUE THREAD

**Issue by niauah** [i3thuan5/kau3-tian2_iong7-ji7#67]
```
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9oVnhv/kau3-tian2-iong7-ji7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9oVnhv/kau3-tian2-iong7-ji7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-5Ygw8j
         cwd: /tmp/pip-install-9oVnhv/kau3-tian2-iong7-ji7/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9oVnhv/kau3-tian2-iong7-ji7/setup.py", line 3
        from 版本 import 版本
             ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sih4sing5hong5** [comment]
`/usr/bin/python`敢是`python3.10`?

**Comment by sih4sing5hong5** [comment]
#69 無用工具--ah，我local開發python3.10嘛無問題，先結案
